### ISSUE TITLE
Build wheel; error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Carathon** [cocktail-collective/cocktail#12]
When trying to install on Linux Mint 21.2 I am getting this error message:

pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/carathon/Downloads/cocktail
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 5, in <module>
          import setuptools.command.build
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by rfletchr** [comment]
Ah OK, you should be careful doing that, your system python can get messed up if your not careful.

try this
``` bash

cd cocktail
python3 -m venv venv
source venv/bin/activate
pip install --upgrade setuptools pip
pip install .
cocktail

```

**Comment by Carathon** [comment]
Alright, thanks for the quick response.
I did as mentioned above and now getting this message:

cocktail
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, wayland, offscreen, minimalegl, xcb, minimal, vkkhrdisplay, eglfs, wayland-egl, vnc.

**Comment by rfletchr** [comment]
I had the same issue with unbuntu (mints built ontop of ubuntu)

```sudo apt install libxcb-cursor0```

**Comment by Carathon** [comment]
Now it is working! Thanks a lot.

**Comment by rfletchr** [comment]
my pleasure :)
